[colors.primary]
background = "#0F1212"  # Black background
foreground = "#E6E9EF"  # Bright white for text

[colors.normal]
black = "#0F1212"       # Black
red = "#FF3B47"         # Bright red
green = "#9E9E9E"       # Gray
yellow = "#B2B2B2"      # Light gray
blue = "#ff5e5e"        # Soft red variant
magenta = "#CF5458"     # Muted red
cyan = "#7A7A7A"        # Gray
white = "#E6E9EF"       # Bright white

[colors.bright]
black = "#292B2B"       # Dim black
red = "#FF5E5E"         # Vivid red
green = "#8C8C8C"       # Mid gray
yellow = "#D6D6D6"      # Light gray
blue = "#F03C4A"        # Bright red variant
magenta = "#FF757A"     # Pinkish red
cyan = "#C4C4C4"        # Gray
white = "#FFFFFF"       # Pure white
