[colors.primary]
background = "#121212"  # Black background
foreground = "#E6E9EF"  # Bright white for text

[colors.normal]
black = "#0F1212"       # Black
red = "#1B2A39"         # Navy blue (subtle red replacement)
green = "#1C3A5D"       # Deep navy blue (grayish blue for green)
yellow = "#2D4A7F"      # Muted navy blue (light gray shift)
blue = "#3C5A8A"        # Navy blue (soft blue)
magenta = "#CF5458"     # Muted red (unchanged)
cyan = "#7A7A7A"        # Gray (unchanged)
white = "#E6E9EF"       # Bright white

[colors.bright]
black = "#292B2B"       # Dim black
red = "#1B2A39"         # Navy blue (vivid red replacement)
green = "#1C3A5D"       # Deep navy blue
yellow = "#3C5A8A"      # Navy blue (light gray shift)
blue = "#2D4A7F"        # Brighter navy blue
magenta = "#FF757A"     # Pinkish red (unchanged)
cyan = "#C4C4C4"        # Gray (unchanged)
white = "#FFFFFF"       # Pure white
