[colors.primary]
background = "#0F1212"
foreground = "#E6E9EF"

[colors.normal]
black = "#0F1212"
red = "#DA344D"
green = "#498E5E"
yellow = "#61be64"
blue = "#269f67"
magenta = "#284f3a"
cyan = "#269f67" # arch logo 

white = "#BBBBBB" 

[colors.bright]
black = "#292B2B"
red = "#f54747"
green = "#269F68"
yellow = "#689d6a"
blue = "#61BE64"
magenta = "#a369ef"
cyan = "#e7d826"

white = "#E6E9EF" # text
